apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ''
    targetRevision: HEAD
    path: manifests
  destination:
    server: ''
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
      - Force=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/ports/0/nodePort
        - /spec/ports/1/nodePort
    - group: apps
      kind: Deployment 